name: "Validate devcontainer-feature.json files"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/*/devcontainer-feature.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Validate devcontainer-feature.json files"
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./src"
